[package]
name = "ys"
version = "0.1.0"
edition = "2021"

[dependencies.clap]
version = "3.2.17"
features = ["derive", "suggestions", "color", "wrap_help"]

[dependencies.syntect]
version = "5.0.0"
default-features = false
features = ["parsing", "default-fancy"]
