name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          key: '**/.pre-commit-config.yaml'

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files
